#!/bin/bash

# A small script to convert audio files
#Copyright © 2020 Käppeler David
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.


Inpu=""
Outpu=""
IFS=$'\n'
DIR="/home/david/$1"
set -f
echo $DIR



convert() {
for line in $(find $DIR -name "*.mp3" | awk "NR%4==$1" | awk -F "\n" '/(mp3)/ {print $0}'); do
	echo $line
	Inpu=$(echo $line | awk -F "\n" '{print $1}')
	Outpu=$(echo $line | awk -F "\n" '/(mp3)/ {sub (/(mp3)/, "opus"); print $0}')
	ffmpeg -hwaccel auto -i $Inpu -c:a libopus -b:a 192k $Outpu
	rm $Inpu
done
}



convert 0 & convert 1 & convert 2 & convert 3
