#!/bin/bash
MONITORBUF="$(xrandr | awk '/\sconnected/{print $1}' | sed -n '2,10 p' | dmenu -i -p "Choose Monitor")"
NUMBERCON=$(xrandr | awk '/\sconnected/{print $1}' | wc -l)
POSITION="--$(echo -e "right-of\nleft-of\nabove\nbelow" | dmenu -i -p "Choose Postition")"

xrandr --output $MONITORBUF --auto $POSITION LVDS1
sleep 1
MONITOR=$MONITORBUF polybar $NUMBERCON &
herbstclient detect_monitors
herbstclient pad 1 25 2 2 2
herbstclient pad 2 25 2 2 2
herbstclient pad 3 25 2 2 2

