#!/bin/bash
multitail -CS irc -f /home/david/irc/irc.rizon.net/#4chan/out -f /home/david/irc/irc.rizon.net/#_g_tech/out -f /home/david/irc/irc.rizon.net/#_g_technology/out -f /home/david/irc/irc.rizon.net/#_g_tv/out
